server:
  port: 8082

spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=VaccinationCenterDB
    username: vishal
    password: system123#
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  application:
    name: VACCINATION-CENTER-SERVICE